### ISSUE TITLE
1.6.5: In Open Rating exists a dummy rate

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#140]
On both devices.

In open rating is a new rating available with following text:
Rating due on
For group

![img_3606](https://user-images.githubusercontent.com/22747157/27542594-fdb7a3fe-5a87-11e7-8a11-4e68421d2e9d.PNG)

Could that be related to a new property in the rating dates, that occurs at the first poistion:

![2017-06-26 15_55_17-aspecx-test realtime database firebase console](https://user-images.githubusercontent.com/22747157/27542715-64724964-5a88-11e7-90ac-4ec211ea05cc.png)

**Comment by xamplo** [comment]
Each group seems to have a dummy 

![screenshot_2017-06-26-16-20-42](https://user-images.githubusercontent.com/22747157/27543844-b10dc228-5a8b-11e7-9421-861fcaf6f500.png)

**Comment by ursmeier-mercatus** [comment]
This is due that 1.6.5 writes the ratings to the wrong node. 
I misspelled the location when I refactored the code.

If I am right, than the user should not see any ratings (done).
Looking at the group, it should be OK, however.

**Comment by ursmeier-mercatus** [comment]
Fixed in 1.6.6

**Comment by xamplo** [comment]
After installing the version 1.6.6, the dummy open rating still exists for the user edo.bezemer@xamplo.com and edo.plato@gmail.com. 

The user edo.bezemer@gmail.com doesn't have any dummy open rates more. 

Enabling more open ratings doesn't generate more dummies for edo.bezemer@xamplo.com.

Is this an exception dummy?

**Comment by ursmeier-mercatus** [comment]
Most probably the old wrong entries. Didn't delete them.
Just test with new projects.

**Comment by xamplo** [comment]
That works fine!

**Comment by xamplo** [comment]
Works now
